[package]
name = "pty"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"

[lib]
crate-type = ["staticlib"]

[dependencies]
ddk = { path = "../../ddk" }

[features]
kernel-imports = ["ddk/kernel-imports"]

[lints.rust]
unsafe_code = "warn"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"
