#! /bin/sh

version=0.0.0.20260718.9
revision=1
git_url="https://github.com/managarm/mlibc.git"
commit="4b09f2f0860cbe20775ab16018320e272564d102"
shallow=yes
source_imagedeps="git meson"
source_hostdeps=""
source_deps=""
source_allow_network=yes

prepare() {
    meson subprojects download freestnd-c-hdrs freestnd-cxx-hdrs frigg libsmarter
}
