#! /bin/sh

version=2.45.1
revision=1
tarball_url="https://ftpmirror.gnu.org/binutils/binutils-${version}.tar.xz"
tarball_sha512="ea030419eba387579ab717be7e3223fc99e93b586860b06003c12489f93441640d4082736f76aa5e98233db4f46e232f536a45e471486de1f5b64e1b827c167e"
imagedeps="build-essential"
hostdeps="pkg-config"

prepare() {
    autotools_recursive_regen
}

configure() {
    "${source_dir}"/configure \
        --prefix="${prefix}" \
        --target=${OS_TRIPLET} \
        --with-sysroot="${sysroot}" \
        --enable-separate-code \
        --enable-cet \
        --enable-default-execstack=no \
        --enable-deterministic-archives \
        --enable-ld=default \
        --enable-new-dtags \
        --enable-plugins \
        --enable-relro \
        --enable-threads \
        --disable-nls \
        --disable-werror \
        --with-pic
}

build() {
    make -j"${parallelism}"
}

package() {
    DESTDIR="${dest_dir}" make install

        strip_command=strip \
    post_package_strip
}
