[package]
name = "roanix"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
spin = "0.9.8"
xmas-elf = "0.9.1"
rustc-demangle = "0.1"
bitflags = "2.8.0"
intrusive-collections = { version = "0.9", default-features = false }
limine = { git = "https://github.com/jasondyoungberg/limine-rs", rev = "99cb96b" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.15.2"
raw-cpuid = "11.2.0"

[target.'cfg(target_arch = "riscv64")'.dependencies]
fdt = "0.1.5"
