#! /bin/sh

version=9.11
revision=1
tarball_url="https://ftp.gnu.org/gnu/coreutils/coreutils-${version}.tar.xz"
tarball_blake2b="bea602b60824724bddd53ef7a232292ddb99f9b940ebedc30bd42f9b2f3d4763e7ea6c1d76c556413261b8c0bba7b1adbb4a5f6619ff3c9bdbe80d05a12ebd86"
imagedeps="build-essential gperf"
hostdeps="bootstrap-gcc binutils"
deps="base"

prepare() {
    autotools_recursive_regen no-autoreconf
}

configure() {
    TARGET_CFLAGS="${TARGET_CFLAGS} -DSLOW_BUT_NO_HACKS"
    FORCE_UNSAFE_CONFIGURE=1 \
    gl_cv_host_operating_system="Roanix" \
        autotools_configure \
            --disable-acl \
            --disable-libcap \
            --disable-nls \
            --disable-xattr \
            --enable-no-install-program="runcon,chroot,df,stat"
}

build() {
    make -j"${parallelism}"
}

package() {
    make install DESTDIR="${dest_dir}"
}
