#! /bin/sh

version=8.3
revision=7
tarball_url="https://ftp.gnu.org/gnu/readline/readline-${version}.tar.gz"
tarball_blake2b="45d6fe7e34c56d309102a94aa776a7f5284201e844450e14ff818df9fa84a72154bdca70f11828c94954b080cbbe4666fa0b00ffa8460118ec8f3ea551b73dad"
imagedeps="build-essential"
hostdeps="bootstrap-gcc binutils"
deps="base ncurses"

prepare() {
    autotools_recursive_regen
}

configure() {
    bash_cv_func_sigsetjmp=missing \
    ac_cv_func_wcwidth=yes \
        autotools_configure \
            --enable-multibyte \
            --with-curses
}

build() {
    make -j"${parallelism}" SHLIB_LIBS="-lncursesw -ltinfow"
}

package() {
    make install-shared install-headers DESTDIR="${dest_dir}"
}
