#! /bin/sh

name=mlibc-headers
from_source=mlibc
revision=2
imagedeps="ninja-build meson build-essential"
deps="linux-headers"

prepare() {
    meson subprojects download freestnd-c-hdrs freestnd-cxx-hdrs frigg libsmarter
}

configure() {
    meson setup build "${source_dir}" \
        --cross-file="${base_dir}/build-support/cross_file-${JINX_ARCH}.txt" \
        --prefix="${prefix}" \
        -Dheaders_only=true \
        -Dlinux_kernel_headers="${build_dir}/builds/linux-headers/stage/include" \
        -Dposix_option=enabled \
        -Dlinux_option=enabled \
        -Dglibc_option=enabled \
        -Dbsd_option=enabled
}

build() {
    ninja -C build
}

package() {
    DESTDIR="${dest_dir}" ninja -C build install
}
