#! /bin/sh

version=3.29.2
revision=2
tarball_url="https://github.com/Kitware/CMake/releases/download/v${version}/cmake-${version}.tar.gz"
tarball_sha512="0dad9e0e3ad9c1178d337cd3a14e9ce145e011175e9d9fce4961d12b8fe37091f9fdf05f4303cdd846408955b11bac3cfe5064f852833b99e31f5a7b82a9d1eb"
imagedeps="build-essential libssl-dev"

configure() {
    "${source_dir}"/bootstrap \
        --prefix="${prefix}" \
        --parallel="${parallelism}"
}

build() {
    make -j"${parallelism}"
}

package() {
    make install DESTDIR="${dest_dir}"

    echo "include(Platform/UnixPaths)" \
        >"${dest_dir}${prefix}/share/cmake-3.29/Modules/Platform/Roanix.cmake"
}
