#! /bin/sh

version=0.1
revision=8
source_dir="drivers"
hostdeps=""

configure() {
    cp -a "${source_dir}"/. .
    make ARCH="${JINX_ARCH}" clean
}

build() {
    make ARCH="${JINX_ARCH}" -j"${parallelism}"
}

package() {
    make \
        ARCH="${JINX_ARCH}" \
        DESTDIR="${dest_dir}" \
        PREFIX="${prefix}" \
        install
}
