#! /bin/sh

skip_pkg_check=yes
version="$(. "${base_dir}/host-recipes/gcc-host/recipe" && echo ${version})"
revision=1
hostdeps="gcc-host pkg-config"
imagedeps="build-essential"
deps="mlibc libgcc"

build() {
    make \
        -C "${build_dir}/host-builds/gcc-host/build" \
        -j"${parallelism}" \
        all-target-libatomic
}

package() {
    cd "${build_dir}"/host-builds/gcc-host/build

    rm -rf tmp_libatomic_dir
    mkdir tmp_libatomic_dir

    DESTDIR="$(realpath tmp_libatomic_dir)" make install-target-libatomic

    mkdir -p "${dest_dir}${prefix}"
    cp -r tmp_libatomic_dir/usr/local/${OS_TRIPLET}/* "${dest_dir}${prefix}"/
}
