#! /bin/sh

skip_pkg_check=yes
version="$(. "${base_dir}/host-recipes/gcc-host/recipe" && echo ${version})"
revision=4
hostdeps="gcc-host pkg-config"
imagedeps="build-essential"
deps="mlibc libgcc"

build() {
    make \
        -C "${build_dir}/host-builds/gcc-host/build" \
        -j"${parallelism}" \
        all-target-libstdc++-v3
}

package() {
    cd "${build_dir}"/host-builds/gcc-host/build

    rm -rf tmp_libstdc++_dir
    mkdir tmp_libstdc++_dir

    DESTDIR="$(realpath tmp_libstdc++_dir)" make install-target-libstdc++-v3

    # For some reason this also installs libgcc even though it shouldn't...
    # Remove it.
    rm -fv tmp_libstdc++_dir/usr/local/${OS_TRIPLET}/lib/libgcc*

    mkdir -p "${dest_dir}${prefix}"

    cp -r tmp_libstdc++_dir/sysroot/usr/include "${dest_dir}${prefix}"/
    cp -r tmp_libstdc++_dir/usr/local/share "${dest_dir}${prefix}"/
    cp -r tmp_libstdc++_dir/usr/local/${OS_TRIPLET}/* "${dest_dir}${prefix}"/
}
